### ISSUE TITLE
Get Specific Customer by Employee ID

### ISSUE THREAD

**Issue by sshJerry** [Kev-Index/QuickBytesOnSpring#12]
Employee IDs are by default 0 so this won't work as expected. Generate random IDs or force Admin to provide employee ID at creation.

**Comment by sshJerry** [comment]
Primitive int as shown here located @quickbytes/backend/model/Customer.java.
![image](https://user-images.githubusercontent.com/25858745/182256867-c2ce44c2-3bfc-4344-bc4c-7dc8110b8568.png)
It is by default zero when not assigned a value. As a result, when a USER is created, they start with a default Employee ID of 0.

How shall we instantiate this value? Random Employee IDs, Ascending IDs from x, or force Admin to provide Employee ID at creation?

**Comment by sshJerry** [comment]
Options
1. Global instance counter
2. Algorithm calculation of IDs
3. Understand Auto Generation. 
4. Remove it

**Comment by Kev-Index** [comment]
Should not be nullable. Will be entered by Admin when creating user.

**Comment by sshJerry** [comment]
Decided to go with Java.util.Random. Employee ID is initialized with random values up to 99999
